name: Deploy Calendar

on:
  push:
    branches:
      - main  # Trigger this workflow when you push to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository code

      - name: Deploy to GitHub Pages
        uses: jamesives/github-pages-deploy-action@v4  # Deploy to GitHub Pages
        with:
          branch: gh-pages  # The branch for GitHub Pages
          folder: .  # Deploy the root folder (adjust if necessary)
        env:
          TOKEN: ${{ secrets.TOKEN }}  # Use the token stored in secrets (ensure secret is named "TOKEN")
