name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # The branch to deploy to (you can change this if you want)
        folder: ./  # The folder to deploy, change this if you need a subfolder to deploy
        token: ${{ secrets.TOKEN }}  # Use your GitHub Personal Access Token here
